<template>
  <Layout>
    <div
      class="calendly-inline-widget"
      data-url="https://calendly.com/cruisers/cruisers-consultation"
      style="min-width:320px;height:630px;"
    ></div>
    <script
      type="application/javascript"
      src="https://assets.calendly.com/assets/external/widget.js"
    ></script>
  </Layout>
</template>
